// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtOFKBQ_C1O_V_1hz-1eS5pSjleHefhrk',
    appId: '1:526051922550:web:e4d706d29cfe6966900557',
    messagingSenderId: '526051922550',
    projectId: 'random-joke-app-65806',
    authDomain: 'random-joke-app-65806.firebaseapp.com',
    storageBucket: 'random-joke-app-65806.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_SSlLbx5hVfZfigjcS4bh-PJcHApXkGw',
    appId: '1:526051922550:android:c1634640aab5e694900557',
    messagingSenderId: '526051922550',
    projectId: 'random-joke-app-65806',
    storageBucket: 'random-joke-app-65806.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ULHeBW0EHY7bxtEut8nG8WndBjpne6o',
    appId: '1:526051922550:ios:54ac3b7e41f3f22a900557',
    messagingSenderId: '526051922550',
    projectId: 'random-joke-app-65806',
    storageBucket: 'random-joke-app-65806.firebasestorage.app',
    iosBundleId: 'com.example.randomJokeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1ULHeBW0EHY7bxtEut8nG8WndBjpne6o',
    appId: '1:526051922550:ios:54ac3b7e41f3f22a900557',
    messagingSenderId: '526051922550',
    projectId: 'random-joke-app-65806',
    storageBucket: 'random-joke-app-65806.firebasestorage.app',
    iosBundleId: 'com.example.randomJokeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtOFKBQ_C1O_V_1hz-1eS5pSjleHefhrk',
    appId: '1:526051922550:web:64494c9bde9aabde900557',
    messagingSenderId: '526051922550',
    projectId: 'random-joke-app-65806',
    authDomain: 'random-joke-app-65806.firebaseapp.com',
    storageBucket: 'random-joke-app-65806.firebasestorage.app',
  );

}